### ISSUE TITLE
Issue in encoding post body (payload) while calling invoke lambdas

### ISSUE THREAD

**Issue by bc-mahesh** [LivePersonInc/faas-client-jdk#20]
The method for sending the payload is wrong in the faas client, it doesn't write the payload to the output stream as utf8 content, as a result inputs with non-english content isn't being processed as expected.

Input:
`{"timestamp":1614363231520,"headers":[],"payload":{"test":"English å ø ñ 🖖 😂 ಕನ್ನಡ"}}`

Output: 
English � � � =� ��ͨ�

This issue is only in the client, when we call the invoke API from postman directly, it works fine. This is the reference to the code where the payload is being sent - https://github.com/LivePersonInc/faas-client-jdk/blob/4ae3e7f47e0755d1824eb501257f8258743890f0/src/main/java/com/liveperson/faas/http/DefaultRestClient.java#L44

**Comment by LivePersonFaas** [comment]
Encoding issue fixed here: https://github.com/LivePersonInc/faas-client-jdk/pull/22  in version 1.1.4
